apiVersion: argoproj.io/v1alpha1
kind: Rollout 
metadata:
  labels:
    app: rollout-demo
  name: rollout-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollout-demo
  strategy:
    blueGreen:
      activeService: rollout-demo-stable
      previewService: rollout-demo-preview
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
        - templateName: rollout-check
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-demo
    spec:
      containers:
      - image: quarkus/rollout-demo:0.0.1
        name: rollout-demo
        ports:
        - containerPort: 8080
        resources: {}
status: {}
